/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSellersRouteImport } from './routes/_app.sellers'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCasesRouteImport } from './routes/_app.cases'
import { Route as AppBuyersRouteImport } from './routes/_app.buyers'
import { Route as AppContactsIndexRouteImport } from './routes/_app.contacts.index'
import { Route as AppCasesIndexRouteImport } from './routes/_app.cases.index'
import { Route as AppContactsContactIdRouteImport } from './routes/_app.contacts.$contactId'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app.cases.$caseId'
import { Route as ApiPublicQboCallbackRouteImport } from './routes/api/public/qbo/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSellersRoute = AppSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyersRoute = AppBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCasesRoute,
} as any)
const AppContactsContactIdRoute = AppContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AppCasesRoute,
} as any)
const ApiPublicQboCallbackRoute = ApiPublicQboCallbackRouteImport.update({
  id: '/api/public/qbo/callback',
  path: '/api/public/qbo/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/buyers': typeof AppBuyersRoute
  '/cases': typeof AppCasesRouteWithChildren
  '/contacts': typeof AppContactsRouteWithChildren
  '/finance': typeof AppFinanceRoute
  '/reports': typeof AppReportsRoute
  '/sellers': typeof AppSellersRoute
  '/settings': typeof AppSettingsRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/cases/': typeof AppCasesIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/api/public/qbo/callback': typeof ApiPublicQboCallbackRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/buyers': typeof AppBuyersRoute
  '/finance': typeof AppFinanceRoute
  '/reports': typeof AppReportsRoute
  '/sellers': typeof AppSellersRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/cases': typeof AppCasesIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/api/public/qbo/callback': typeof ApiPublicQboCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/buyers': typeof AppBuyersRoute
  '/_app/cases': typeof AppCasesRouteWithChildren
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/finance': typeof AppFinanceRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sellers': typeof AppSellersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/_app/contacts/$contactId': typeof AppContactsContactIdRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/api/public/qbo/callback': typeof ApiPublicQboCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buyers'
    | '/cases'
    | '/contacts'
    | '/finance'
    | '/reports'
    | '/sellers'
    | '/settings'
    | '/cases/$caseId'
    | '/contacts/$contactId'
    | '/cases/'
    | '/contacts/'
    | '/api/public/qbo/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/buyers'
    | '/finance'
    | '/reports'
    | '/sellers'
    | '/settings'
    | '/'
    | '/cases/$caseId'
    | '/contacts/$contactId'
    | '/cases'
    | '/contacts'
    | '/api/public/qbo/callback'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/buyers'
    | '/_app/cases'
    | '/_app/contacts'
    | '/_app/finance'
    | '/_app/reports'
    | '/_app/sellers'
    | '/_app/settings'
    | '/_app/'
    | '/_app/cases/$caseId'
    | '/_app/contacts/$contactId'
    | '/_app/cases/'
    | '/_app/contacts/'
    | '/api/public/qbo/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicQboCallbackRoute: typeof ApiPublicQboCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sellers': {
      id: '/_app/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof AppSellersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buyers': {
      id: '/_app/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof AppBuyersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/_app/contacts/$contactId': {
      id: '/_app/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AppContactsContactIdRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/api/public/qbo/callback': {
      id: '/api/public/qbo/callback'
      path: '/api/public/qbo/callback'
      fullPath: '/api/public/qbo/callback'
      preLoaderRoute: typeof ApiPublicQboCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCasesRouteChildren {
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
}

const AppCasesRouteChildren: AppCasesRouteChildren = {
  AppCasesCaseIdRoute: AppCasesCaseIdRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
}

const AppCasesRouteWithChildren = AppCasesRoute._addFileChildren(
  AppCasesRouteChildren,
)

interface AppContactsRouteChildren {
  AppContactsContactIdRoute: typeof AppContactsContactIdRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsContactIdRoute: AppContactsContactIdRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppRouteChildren {
  AppBuyersRoute: typeof AppBuyersRoute
  AppCasesRoute: typeof AppCasesRouteWithChildren
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppFinanceRoute: typeof AppFinanceRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSellersRoute: typeof AppSellersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuyersRoute: AppBuyersRoute,
  AppCasesRoute: AppCasesRouteWithChildren,
  AppContactsRoute: AppContactsRouteWithChildren,
  AppFinanceRoute: AppFinanceRoute,
  AppReportsRoute: AppReportsRoute,
  AppSellersRoute: AppSellersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicQboCallbackRoute: ApiPublicQboCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
